# -*- coding: utf-8 -*-
"""multi-financial-agents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/virattt/2b1355a14a1129a9d0fbd707708815e5/multi-financial-agents.ipynb

This notebook provides a tutorial on how to use multi-agents with LangGraph.

Specifically, we use the **supervisor** pattern, where we have 1 supervisor agent and 2 analyst agents:
1. web analyst (does web searching)
2. financial analyst (does financial search)

This code will be a part of an evolving series.

If you have any questions, please message me on X at [virattt](https://twitter.com/virattt).

# Setup
"""

import getpass
import os
from dotenv import load_dotenv

load_dotenv()


def _set_if_undefined(var: str):
    if not os.environ.get(var):
        os.environ[var] = getpass.getpass(f"Please provide your {var}")


_set_if_undefined("OPENAI_API_KEY")               # Get from https://platform.openai.com
_set_if_undefined("FINANCIAL_DATASETS_API_KEY")   # Get from https://financialdatasets.ai
_set_if_undefined("TAVILY_API_KEY")               # Get from https://tavily.com

"""# Create tools"""

from typing import Annotated

from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_experimental.tools import PythonREPLTool

tavily_tool = TavilySearchResults(max_results=5)

# This executes code locally, which can be unsafe
python_repl_tool = PythonREPLTool()

"""# Helper functions"""

from langchain_core.messages import HumanMessage


def agent_node(state, agent, name):
    result = agent.invoke(state)
    return {
        "messages": [HumanMessage(content=result["messages"][-1].content, name=name)]
    }

"""# Create Agent Supervisor"""

from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_openai import ChatOpenAI
from pydantic import BaseModel
from typing import Literal

members = ["web_analyst", "financial_analyst"]
system_prompt = (
    "You are a supervisor tasked with managing a conversation between the"
    " following analysts:  {members}. Given the following user request,"
    " respond with the analyst to act next. Each analyst will perform a"
    " research task on 1 ticker only and respond with their results and status. When finished,"
    " respond with FINISH."
)

options = ["FINISH"] + members

class routeResponse(BaseModel):
    next: Literal["FINISH", "web_analyst", "financial_analyst"]  # Fixed line: explicit literals instead of *options

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_prompt),
        MessagesPlaceholder(variable_name="messages"),
        (
            "system",
            "Given the conversation above, who should act next?"
            " Or should we FINISH? Select one of: {options}",
        ),
    ]
).partial(options=str(options), members=", ".join(members))

llm = ChatOpenAI(model="gpt-4o")

def supervisor_agent(state):
    supervisor_chain = prompt | llm.with_structured_output(routeResponse)
    return supervisor_chain.invoke(state)

"""# Construct Graph"""

import functools
import operator
from typing import Sequence
from typing_extensions import TypedDict

from langchain_community.tools import IncomeStatements, BalanceSheets, CashFlowStatements
from langchain_community.utilities.financial_datasets import FinancialDatasetsAPIWrapper

from langchain_core.messages import BaseMessage

from langgraph.graph import END, StateGraph, START
from langgraph.prebuilt import create_react_agent


# The agent state is the input to each node in the graph
class AgentState(TypedDict):
    # The annotation tells the graph that new messages will always
    # be added to the current states
    messages: Annotated[Sequence[BaseMessage], operator.add]
    # The 'next' field indicates where to route to next
    next: str


# Create the web_analyst
web_analyst = create_react_agent(llm, tools=[tavily_tool])
web_analyst_node = functools.partial(agent_node, agent=web_analyst, name="web_analyst")

# Create the financial_analyst
api_wrapper = FinancialDatasetsAPIWrapper()
financial_tools = [IncomeStatements(api_wrapper=api_wrapper), BalanceSheets(api_wrapper=api_wrapper), CashFlowStatements(api_wrapper=api_wrapper)]
financial_analyst = create_react_agent(llm, tools=financial_tools)
financial_analyst_node = functools.partial(agent_node, agent=financial_analyst, name="financial_analyst")

workflow = StateGraph(AgentState)
workflow.add_node("web_analyst", web_analyst_node)
workflow.add_node("financial_analyst", financial_analyst_node)
workflow.add_node("supervisor", supervisor_agent)

# Connect edges of the graph
for member in members:
    # We want our workers to ALWAYS "report back" to the supervisor when done
    workflow.add_edge(member, "supervisor")
# The supervisor populates the "next" field in the graph state
# which routes to a node or finishes
conditional_map = {k: k for k in members}
conditional_map["FINISH"] = END
workflow.add_conditional_edges("supervisor", lambda x: x["next"], conditional_map)
# Finally, add entrypoint
workflow.add_edge(START, "supervisor")

graph = workflow.compile()

"""# Invoke the Agent Team"""

for s in graph.stream(
    {"messages": [HumanMessage(content="What is the latest news and revenue for AAPL?")]},
    {"recursion_limit": 10},
):
    if "__end__" not in s:
        print(s)
        print("----")