"""Standalone diagnostic for `MarkdownTool`."""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from stockbot.tools.data import MarkdownTool
from stockbot.tools.tests.common import (
    execute_tool,
    load_environment,
    render_report,
    shutdown_executor,
)


def main() -> None:
    parser = argparse.ArgumentParser(description="Test markdown file output")
    parser.add_argument(
        "--text",
        default="# Sample Report\n\nGenerated by MarkdownTool.",
        help="Markdown text to write",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=4.0,
        help="Execution timeout in seconds",
    )
    args = parser.parse_args()

    load_environment()
    tool = MarkdownTool()
    original_cwd = Path.cwd()
    with tempfile.TemporaryDirectory() as tmp:
        try:
            os.chdir(tmp)
            outcome = execute_tool(tool.run, args.text, timeout=args.timeout)
        finally:
            os.chdir(original_cwd)

    print(render_report("MarkdownTool", outcome))
    shutdown_executor()


if __name__ == "__main__":
    main()
